language: node_js
os:
  - windows
  - linux
  - osx
node_js:
  - "11"
  - "10"
before_script:
  - choco install jdk11
  - export PATH=$PATH:"/c/Program Files/Java/jdk-11.0.1/bin"

script:
  - npm run lint
  - npm run coverage
  - codecov
