language: node_js
os:
  - windows
node_js:
  - "11"
before_script:
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then choco install jdk11; fi
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then export PATH=$PATH:"/c/Program Files/Java/jdk-11.0.1/bin"; fi

script:
  - npm run lint
  - npm run coverage
  - codecov
